### ISSUE TITLE
METSENSOR tweaks

### ISSUE THREAD

**Issue by maxlk96** [minsulander/vatiris#13]
- Empty row between COMP and RVR (see pics)
- Suggestion: RVR only bold when less than 2000m(?)
- Sometimes the last decimal of QNH is not bold, maybe something to check?
- RH is shown as HUM (iaf på bild från Stockholm APP), also a percent sign is shown after the value.

**Comment by minsulander** [comment]
Bra förslag, ska bli 🫡

**Comment by minsulander** [comment]
Fixat!
