### ISSUE TITLE
Unable to login to vatsim

### ISSUE THREAD

**Issue by VikHolger** [minsulander/vatiris#14]
Vid försök av inloggning till wiki så tillåter fierfox ej att man loggar in.
Vet ej om det går lösas ¯\ _(ツ)_/¯

> Firefox Kan inte öppna den här sidan

> För att skydda din säkerhet tillåter auth.vatsim.net inte Firefox att visa sidan om en annan webbplats har den inbäddad. För att se den här sidan måste du öppna den i ett nytt fönster. [Läs mer...](https://support.mozilla.org/1/firefox/127.0.2/WINNT/sv-SE/xframe-neterror-page)

![bild](https://github.com/user-attachments/assets/eda54efe-0c38-4c40-9fff-1130f10d01be)

**Comment by minsulander** [comment]
Tack för rapporten! 
Samma problem som i #9, auth.vatsim.net tillåter inte iframe...
