### ISSUE TITLE
High update rate data feed

### ISSUE THREAD

**Issue by maxlk96** [minsulander/vatiris#15]
To prevent delays in ATIS letter update etc.

Such as on https://simaware.ca/
(Not sure if the smooth moving aircraft is by interpolation or or actually higher updater rate than what whatever vatscope is using @minsulander ?)

Could partially replace the need for a Euroscope plugin.

**Comment by minsulander** [comment]
VATSIM data from the JSON API https://vatsim.dev/api/data-api/get-network-data is available at 15 second intervals.
SimAware fetches data with 15s interval and does extrapolation with 1s interval, hence the "apparent high update rate" but in some cases also resulting in aircraft flying backwards/sideways. 😉 

For ATIS letter update delays my experience with EuroScope is that it too has quite a bit of lag so I don't know how much a Euroscope plugin would help actually...

**Comment by maxlk96** [comment]
> VATSIM data from the JSON API https://vatsim.dev/api/data-api/get-network-data is available at 15 second intervals. SimAware fetches data with 15s interval and does extrapolation with 1s interval, hence the "apparent high update rate" but in some cases also resulting in aircraft flying backwards/sideways. 😉
> 
> For ATIS letter update delays my experience with EuroScope is that it too has quite a bit of lag so I don't know how much a Euroscope plugin would help actually...

Ahh got it, 15s should definitely be high enough rate to use for ATIS letter updates, it might even be better than ES 😁

**Comment by minsulander** [comment]
Implemented with 15s interval.
