### ISSUE TITLE
Sector occupancy bars

### ISSUE THREAD

**Issue by maxlk96** [minsulander/vatiris#17]
Window Header: TMA/SI - Occupancy

As Topskys "STS -> Predicted Traffic".

In Stockholm one for entire TMA avbl (probably only APP AoR), also by position (E, W, S etc) 

- [x] Data from VATSIMs datafeed, including prefiles as brighter blue color
- [x] Parsing routes in ETA calculation(?) 
- [x] Backend worker to periodically run FDP scripts and publish data
- [x] Save history (last 30 mins or so)
- [x] VatIRIS store, refreshing etc
- [x] VatIRIS presentation of occupancy bars
- [x] Admin view for FDP data
- [x] Improve FDP scripts with assumed SID/STAR/approach based on runway configuration from ATIS/WX/winds
- [ ] (ES Plugin to use FLEG data/accessing Topsky predicted traffic data) (this should probably be a separate issue)

**Comment by maxlk96** [comment]
Including possibility in (future) admin view to update airspace data by uploading ESE+SCT file, parsing locally before, or after upload on server side.

**Comment by maxlk96** [comment]
Arvid: 

> Vi har kapacitetsvärden för varje godkänd sektorkombination som underlag för när vi ska öppna **(visas som streck på
occupancystaplarna)** men de säger inte alltid hela sanningen. Även om Peakvärdet för 23W45 är 19 kan man ibland sitta med 25st utan att det är några problem och andra dagar börja svettas redan vid 15

Something to implement, similar to TopSky, having the oportunity to change the value, but having them pre-filled with values depending on the sector combination.

Need graphical reference how it looks, if not already available(?) @minsulander

**Comment by minsulander** [comment]
Yes that's a great idea, but it's a new feature so I think it deserves a new issue rather than reopening a closed one.
