### ISSUE TITLE
AIP charts

### ISSUE THREAD

**Issue by minsulander** [minsulander/vatiris#2]
Quick access to AIP charts through documents menu.
Have applied for Chartfox API... that might be a nice route to implementation.
Simpler version is a structured menu with links that open in separate tab... but that would have to be maintained (link breakage every so often?) and not as nice...

**Comment by minsulander** [comment]
The Chartfox API seems broken... all I get is this: `{"message":"The dark mode field must be true or false.","errors":{"darkMode":["The dark mode field must be true or false."]}}` when trying out their own examples.

**Comment by minsulander** [comment]
AIP documents from LFV website are iframeable.. the only concern is how to index them and avoid broken links. Maybe implement a webcrawler...

**Comment by maxlk96** [comment]
> The Chartfox API seems broken... all I get is this: `{"message":"The dark mode field must be true or false.","errors":{"darkMode":["The dark mode field must be true or false."]}}` when trying out their own examples.

Posted about this on the Chartfox Discord
https://discord.com/channels/870984092093665300/1263403449224265771/1263403449224265771

**Comment by VikHolger** [comment]
Should be fixed now (awnser from one of the staff on the chart fox community)
![Screenshot_20240720-203120](https://github.com/user-attachments/assets/71dd8ead-938b-4ced-91b8-b9b4566fd05f)
