### ISSUE TITLE
Optionally snap windows, or disallow overlap

### ISSUE THREAD

**Issue by Sjolus** [minsulander/vatiris#23]
It would be sweet if the windows could snap together or not allow overlap.

An option for this could be considered, since sometimes I guess some users would want overlaps etc.

**Comment by maxlk96** [comment]
+1 on snapping

https://github.com/nextapps-de/winbox/discussions/66

https://github.com/lf2com/magnet.js/tree/master

**Comment by minsulander** [comment]
Nice idea. Might be doable just by setting a snapping threshold (like 5 pixels) and knowing all the x/y/width/height of all the windows (which I think we should be able to). Using a grid and snap-to-grid feature would also be an option.. will look into it.

**Comment by minsulander** [comment]
Did some testing on this... will be doable. Just gotta find a nice time slot and a cold drink to work on it for a while.
