### ISSUE TITLE
Aircraft types

### ISSUE THREAD

**Issue by minsulander** [minsulander/vatiris#3]
Implement a quick-n-easy way to search aircraft types and get info on wingspan etc etc...

Like ze germans have done.

https://github.com/vatger/atciss/blob/main/contrib/ac-data/ac-data.json

**Comment by minsulander** [comment]
Just importing ICAO_Aircraft.json from the swedish GNG package and making a nice quick search window for it is probably sufficient to start with... don't need to go the whole database/backend route for this.

**Comment by Kalln** [comment]
Currently not working actively with this due to another project took priority.

Feel free to continue with this. I will pick it up in a couple of weeks if it hasn't been resolved yet by then
