### ISSUE TITLE
Personal settings

### ISSUE THREAD

**Issue by maxlk96** [minsulander/vatiris#43]
- [x] Enable/disable METSENSOR blue flash
- [x] METREPORT blue flash
- [x] Activate/deactivate PLS Integration (and PLS Logic selection #44 )
- [ ] Show/hide raw metar in metreport window https://github.com/minsulander/vatiris/commit/c7ef0b11e5ea12482cf81364ad86efef03572ed7
- [ ]  Show/hide "RWY IN USE" in metreport window
- [X] ~Show/hide "debug timestamp" in top right corner (in windows with dynamic information).~ (will be irrelevant because changing it so that timestamps are only shown when information is outdated in 993b2fa)
- [ ] Managing presets in the settings window? (#27)

More?

**Comment by minsulander** [comment]
These have either been implemented or made irrelevant... except the last one maybe, but it has its own issue.
Closing.
