### ISSUE TITLE
Show online vatsim ATIS in metreport window

### ISSUE THREAD

**Issue by minsulander** [minsulander/vatiris#6]
...to prevent confusion.
Maybe parse vatsim atis text and highlight if using different runway configuration than IRL.

**Comment by maxlk96** [comment]
Possibility of changing between viewing VATSIM and AWOS/IRL datafeed with a "V/R" button added as winbox custom control, highlighting the letter for the feed that is shown

**Comment by minsulander** [comment]
I have implemented a version of this. It works for ESGG. Dry coded same thing for ESSA, let's hope it works.
It now shows rwy in use text as grey if VATSIM ATIS matches, in orange if VATSIM ATIS differs.
Black (as before) if there is no VATSIM ATIS.
Leaving this open until verified that it works on ESSA.

**Comment by minsulander** [comment]
Appears to work as intended

**Comment by minsulander** [comment]
Implemented in https://github.com/minsulander/vatiris/commit/fbd4d85f8758c2befac3e1c90285223d5d161794
