### ISSUE TITLE
Metreport styling and bold text

### ISSUE THREAD

**Issue by minsulander** [minsulander/vatiris#7]
- [X] Issuing time bold
- [X] QNH size/bold
- [X] ID letter bold
- [X] ID letter hidden for non-ATIS airports
- [x] Blue flash
- [x] Text remains blue 1-2 min after flash (click text to acknowledge)
- [ ] More compact view (https://github.com/minsulander/vatiris/commit/a78cc72b9bbea4e386eb00ec67dc1e55a6b26328)
- [x] Hiding raw METAR in the bottom
- [x] QNH Trend arrow

QNH större font, fetstil
Aktiv bokstav fetstil - inte fetstil Sthlm IRL - men kanske ha så ändå..
Trendpilen går kanske att få till om wx store jämför mellan uppdateringarna och sparar nånstans…

**Comment by maxlk96** [comment]
Removing ATIS letter (from AWOS) for airports without ATIS

**Comment by maxlk96** [comment]
QNH trend arrow using https://aviationweather.gov/cgi-bin/data/metar.php?ids=XXXX&hours=2
solving the issue of needing to store data and trend missing before first change happens

Unicode symbols for trend: ⯅⯆⯈


And: blue flash for update, maybe all text remains blue for 1-2 minutes, clickable to acknowledge update. (see DM with description from Arvid)
