### ISSUE TITLE
Remove unnecessary newlines in ARPT COND/NOTAM data

### ISSUE THREAD

**Issue by Sjolus** [minsulander/vatiris#78]
Sometimes the AWOS-data has an unnecessary newline (probably based on character limits per row irl?) in the ARPT COND/NOTAM fields.

Not something we need, can we strip newlines from ARPT COND/NOTAM data, but make sure we always have at least one empty space between the old end of line 1 and the old start of line 2. Would simplify a lot when we enter the data in vATIS.

Example from ESMS, but this also happens sometimes at ESGG:
![image](https://github.com/user-attachments/assets/8067e9da-d02d-4cc6-8825-1141277e6b75)

**Comment by maxlk96** [comment]
Yes, it's because format is kept as received from AWOS!

I'd assume this is an "easy fix"

**Comment by minsulander** [comment]
Resolved in #81
