### ISSUE TITLE
ECFMP flow measures

### ISSUE THREAD

**Issue by minsulander** [minsulander/vatiris#8]
ECFMP [https://ecfmp.vatsim.net/dashboard/flow-measures](https://ecfmp.vatsim.net/dashboard/flow-measures "‌") (eller om man kan integrera med [deras API](https://ecfmp.vatsim.net/dashboard/user-guide/api "‌") att ha en lista som visar nuvarande flow measures)

- [ ] Highlighting row when relevant ADEP/ADES present in filters using cidsi data
- [x] Adding flow measure link in identifier field
- [x] Adding button to creation of new flow measure
- [ ] Filtering/highlighting by FAO (`notified_flight_information_regions`, ESAA is "19"), or using that value in another good way
- [ ] Warning/notification when (or shortly before) a relevant flow measure becomes active (or a new relevant one is added) similar to blue flash
- [ ] Style minimum table width (to prevent strange wrapping)
- [ ] Filtering notified/not-notified (more than 24h in future https://ecfmp.vatsim.net/docs/v1#tag/Flow-Measures)

**Comment by maxlk96** [comment]
https://github.com/minsulander/vatiris/commit/4c9375cc0b844f922f3a23df037127d57daa98aa

**Comment by maxlk96** [comment]
Initial implementation https://github.com/minsulander/vatiris/commit/4c9375cc0b844f922f3a23df037127d57daa98aa

**Comment by maxlk96** [comment]
Possibly filtering measures by `notified_flight_information_regions` (ESAA is "19"), or using that value in another good way..
