### ISSUE TITLE
Unable to delete preset

### ISSUE THREAD

**Issue by prosch35k** [minsulander/vatiris#80]
I can not delete my previously created presets
Also a suggestion to add so you can rename existing presets.

**Comment by maxlk96** [comment]
@prosch35k What happens when you try and delete a preset?

First you have to select it in order to "load" it, then the delete option should work in the submenu.

**Comment by prosch35k** [comment]
I open and load the preset, I click delete preset, I confirm that I want to delete, then confirmation window dissapears and absolutely nothing happens.

**Comment by maxlk96** [comment]
@prosch35k 

You're right, I experience the same behavior, the preset remains in the list and does not get removed!
