### ISSUE TITLE
Better Metreport UI

### ISSUE THREAD

**Issue by prosch35k** [minsulander/vatiris#86]
![VatIRIS förslag](https://github.com/user-attachments/assets/7d7ca135-6753-47ab-9067-320d75143538)

Förslag på hur Metreport fönstret kan förbättras för att ha all viktigast information samlad på en plats,
samt en lista som är lite enklare att förstå.
Lite mera lättläst.

**Comment by maxlk96** [comment]
Först och främst kudos för snyggt förslag @prosch35k !

Jag tog detta med Insulander och vi är överens om att försöka hålla VatIRIS "As Real As Is Technically Possible" med dom funktioner där det finns en IRL-motsvarighet, därför kommer vi inte att "snygga till" metreport-vyn, även om det är ett snyggt och bra förslag.

Om du är osäker på vilken bokstav som representerar vilken källa så får du en tooltip när du håller musen över respektive källvals-knapp, det kanske kan vara en vanesak också?

Just detta kombinerade fönster har vi väldigt bra referensmaterial som vi kunnat utgå ifrån, därför ser det ut (i princip) exakt som fönstret gör IRL!

**Comment by maxlk96** [comment]
Not completely out of the question, maybe for a future "enhanced mode", now prioritising IRL features.
