### ISSUE TITLE
ESSB showing multiple times in 'Documents > Wiki > LOP'

### ISSUE THREAD

**Issue by Kalln** [minsulander/vatiris#87]
List don't filter as expected.

ESSB is always shown no matter the input and shown multiple times. All the links works and refer to the correct document.

![firefox_7YkJbYX12c](https://github.com/user-attachments/assets/9daadb57-f3e7-49da-a4ab-774fcb23d507)
![firefox_H9OQNQGDiv](https://github.com/user-attachments/assets/09f65d13-f6fa-4841-a391-ced46f69eff6)

**Comment by minsulander** [comment]
It's because of the recent lack of manning ESSB_TWR. VatIRIS has its subtle ways. 😉
