### ISSUE TITLE
VATSCA Wiki, (Documentation GOP, LOP, LOA etc)

### ISSUE THREAD

**Issue by minsulander** [minsulander/vatiris#9]
VATSCA wiki doesn't work with iframe so probably needs to be links that open in separate tab...

Preferred method using Wiki API with token.

- [ ] Styling bleeding through?
- [ ] Clickable table of contents

**Comment by blt950** [comment]
@minsulander Could you send me the CORS error you probably get when trying to do this? I'll then see what kind of adjustments I need to do to allow your site to iframe it.

Daniel / VATSCA Web Team

**Comment by minsulander** [comment]
Sure, thanks for helping out @blt950!

Chrome says this in the console:
`Refused to frame 'https://wiki.vatsim-scandinavia.org/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' https://moodle.vatsim-scandinavia.org".`

I suspect it has to do with this header that the wiki webserver responds with:
`Content-Security-Policy: frame-ancestors 'self' https://moodle.vatsim-scandinavia.org`

I've added a Wiki option to the top menubar at https://vatiris.se/ so if you go there, click on that, it'll open a window with an iframe that tries to load https://wiki.vatsim-scandinavia.org/shelves/atc-sweden.

**Comment by blt950** [comment]
I've added an exception for vatiris.se domain now, seems to work now :)

**Comment by minsulander** [comment]
Great stuff, thanks @blt950!
Now we just have the same problem with auth.vatsim.net if we still want to go the iframe route... :crying_cat_face:

**Comment by maxlk96** [comment]
https://forum.vatsim.net/t/iframing-vatsim-connect/6040

https://auth.vatsim.net/organization
